Repository startersclan/docker-sourceservers, pull requests merged in 2022-10, with the labels that each got.

#31 Refactor (ci): Bump `.circleci/config.yml` VM image to `ubuntu-2004:2022.07.1`
  .circleci/config.yml
Labels: area/ci, refactor

#32 Refactor (ci): Bump `azure-pipelines.yml` VM image to `ubuntu-20.04`
  azure-pipelines.yml
Labels: area/ci, refactor

#33 Refactor (ci): Restore `.travis.yml` YAML indentation to classic format
  .travis.yml
Labels: area/ci, refactor

#34 Refactor (ci): Fix indentation of process variables lines in `.gitlab-ci.yml` and `.circleci/config.yml`
  .circleci/config.yml
  .gitlab-ci.yml
Labels: area/ci, refactor, fix

#35 Refactor (ci): Bump `azure-pipelines.yml` job timeout to 120m
  azure-pipelines.yml
Labels: area/ci, refactor

#36 Refactor (ci): Streamline CI files for improved reusability and reliability of code
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  azure-pipelines.yml
Labels: area/ci, refactor

#37 Fix (ci): Add missing matching `services` image `docker:18.09.2-dind` for `.gitlab-ci.yml` `build-image` job
  .gitlab-ci.yml
Labels: area/ci, fix

#38 Fix (test): Add test to verify game version of the game image matches the value of `GAME_VERSION`
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  azure-pipelines.yml
  test/hlds-cstrike
  test/hlds-czero
  test/hlds-dmc
  test/hlds-dod
  test/hlds-gearbox
  test/hlds-ricochet
  test/hlds-tfc
  test/hlds-valve
  test/srcds-csgo
  test/srcds-cstrike
  test/srcds-dod
  test/srcds-hl2mp
  test/srcds-left4dead
  test/srcds-left4dead2
  test/srcds-tf
  test/test-game-image-game-version.sh
  test/test-game-image.sh
Labels: area/ci, fix, area/tests

#41 Fix (test): Add test to verify game version of the game image matches the value of `GAME_VERSION` (continued)
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  azure-pipelines.yml
Labels: area/ci, fix, area/tests

#40 Refactor (ci): Standardize order of CI variables
  .circleci/config.yml
  .gitlab-ci.yml
Labels: area/ci, refactor

#42 Feature (ci): Use `build.sh` for local and CI builds
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  azure-pipelines.yml
  build.sh
Labels: area/ci, feature, refactor

#43 Refactor (ci): Tweak order of `send-notification` job keys in `.gitlab-ci.yml`
  .gitlab-ci.yml
Labels: area/ci, refactor

#44 Refactor (ci): Simplify uses of shell variable expansion
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  azure-pipelines.yml
  build.sh
Labels: area/ci, refactor

#45 Refactor (ci): Use same variable name for docker build contexts
  build.sh
Labels: area/ci, refactor

#46 Refactor (ci): Tweak formatting of `docker build` command for `update` pipeline
  build.sh
Labels: area/ci, refactor

#47 Docs (ci): Tweak comments on CI variables section in `build.sh`
  build.sh
Labels: docs, area/ci

#48 Refactor (ci): Use `notify.circleci.sh` for `.circleci/config.yml` `send-notification` job
  .circleci/config.yml
  notify.circleci.sh
Labels: area/ci, refactor

#49 Refactor (ci): Use `notify.circleci.sh` for `.circleci/config.yml` `send-notification` job (2)
  .circleci/config.yml
  notify.circleci.sh
Labels: area/ci, refactor

#50 Refactor (ci): Use `notify.sh` for `.gitlab-ci.yml` `send-notification` job
  .gitlab-ci.yml
  notify.sh
Labels: area/ci, refactor

#51 Refactor (ci): Simplify sending of build notification on circleci
  .circleci/config.yml
  notify.circleci.sh
Labels: area/ci, refactor

#52 Refactor (ci): Tweak indentation of build notification in `notify.circleci.sh`
  notify.circleci.sh
Labels: area/ci, refactor

#53 Refactor (ci): Simplify error handling in `notify.circleci.sh`
  notify.circleci.sh
Labels: area/ci, refactor

#55 Refactor (ci): Simplify error handling in `notify.sh`
  notify.sh
Labels: area/ci, refactor

#56 Feature (ci): Add `.github/workflows/ci-master-pr.yml`
  .github/workflows/ci-master-pr.yml
Labels: area/ci, feature

#57 Fix (ci): Fix github workflow to trigger on `master`
  .github/workflows/ci-master-pr.yml
Labels: area/ci, fix

#58 Docs (ci): Add default values for build and update variables under CI variables section in `build.sh`
  build.sh
Labels: docs, area/ci

#59 Fix (ci): Bump `.travis.yml` VM image to `jammy` for docker buildkit support
  .travis.yml
Labels: area/ci, fix

#60 Refactor (ci): Simplify relaying of build status in gitlab-ci
  .gitlab-ci.yml
  notify.sh
Labels: area/ci, refactor

#61 Fix (ci): Fix error handling in circleci `Send notification` step
  .circleci/config.yml
Labels: area/ci, fix

#62 Refactor (ci): Streamline `notify.sh` with code from `notify.circleci.sh`
  notify.sh
Labels: area/ci, refactor

#64 Fix (ci): Fix relaying of artifacts on gitlab-ci
  .gitlab-ci.yml
Labels: area/ci, fix

#65 Refactor (ci): Use `notify.sh` for gitlab-ci and circleci
  .circleci/config.yml
  .gitlab-ci.yml
  notify.circleci.sh
  notify.sh
Labels: area/ci, refactor

#66 Refactor (ci): Bump gitlab-ci `send-notification` job image to `alpine:3.14.8`
  .gitlab-ci.yml
Labels: area/ci, refactor

#67 Docs (ci): Use branch names for pipeline badge titles
  .generate/Generate-GameImageRepositoryReadme.ps1
  README.md
  docs/readme/image/hlds-cstrike.md
  docs/readme/image/hlds-czero.md
  docs/readme/image/hlds-dmc.md
  docs/readme/image/hlds-dod.md
  docs/readme/image/hlds-gearbox.md
  docs/readme/image/hlds-ricochet.md
  docs/readme/image/hlds-tfc.md
  docs/readme/image/hlds-valve.md
  docs/readme/image/srcds-csgo.md
  docs/readme/image/srcds-cstrike.md
  docs/readme/image/srcds-dod.md
  docs/readme/image/srcds-hl2mp.md
  docs/readme/image/srcds-left4dead.md
  docs/readme/image/srcds-left4dead2.md
  docs/readme/image/srcds-tf.md
Labels: docs, area/ci

#68 Docs (ci): Add `master` branch build status badge
  .generate/Generate-GameImageRepositoryReadme.ps1
  README.md
  docs/readme/image/hlds-cstrike.md
  docs/readme/image/hlds-czero.md
  docs/readme/image/hlds-dmc.md
  docs/readme/image/hlds-dod.md
  docs/readme/image/hlds-gearbox.md
  docs/readme/image/hlds-ricochet.md
  docs/readme/image/hlds-tfc.md
  docs/readme/image/hlds-valve.md
  docs/readme/image/srcds-csgo.md
  docs/readme/image/srcds-cstrike.md
  docs/readme/image/srcds-dod.md
  docs/readme/image/srcds-hl2mp.md
  docs/readme/image/srcds-left4dead.md
  docs/readme/image/srcds-left4dead2.md
  docs/readme/image/srcds-tf.md
Labels: docs, area/ci

#70 Refactor (ci): Use `ubuntu-20.04` instead of `ubuntu-latest` in github workflow runs
  .github/workflows/ci-master-pr.yml
Labels: area/ci, refactor

#72 Docs (readme): Tweak various sections
  .generate/Generate-GameImageRepositoryReadme.ps1
  README.md
  docs/readme/image/hlds-cstrike.md
  docs/readme/image/hlds-czero.md
  docs/readme/image/hlds-dmc.md
  docs/readme/image/hlds-dod.md
  docs/readme/image/hlds-gearbox.md
  docs/readme/image/hlds-ricochet.md
  docs/readme/image/hlds-tfc.md
  docs/readme/image/hlds-valve.md
  docs/readme/image/srcds-csgo.md
  docs/readme/image/srcds-cstrike.md
  docs/readme/image/srcds-dod.md
  docs/readme/image/srcds-hl2mp.md
  docs/readme/image/srcds-left4dead.md
  docs/readme/image/srcds-left4dead2.md
  docs/readme/image/srcds-tf.md
Labels: docs

#73 Docs (readme): Fix link to `build/Dockerfile` base image reference
  README.md
Labels: docs, fix

#74 Fix (ci): Fix shebang in `build.sh` and `notify.sh`
  build.sh
  notify.sh
Labels: area/ci, fix

#75 Fix (ci): Execute `build.sh` within the script's context on github workflows
  .github/workflows/ci-master-pr.yml
Labels: area/ci, fix

#76 Docs (Dockerfile): Improve documentation on the functions of each
  build/Dockerfile
  update/Dockerfile
Labels: docs

#77 Docs (readme): Tweak write-up on `ENTRYPOINT` and `CMD`
  README.md
Labels: docs

#78 Refactor (ci): Remove unnecessary uses of shell variable expansion
  build.sh
Labels: area/ci, refactor

#79 Refactor (ci): Use single-quoted strings where possible in `build.sh` and `notify.sh`
  build.sh
  notify.sh
Labels: area/ci, refactor

#80 Refactor (ci): Simplify shell dot source syntax
  .github/workflows/ci-master-pr.yml
Labels: area/ci, refactor

#81 Refactor (test): Add `STEAM_LOGIN` variable to `.env` files
  test/build-hlds-cstrike.env
  test/build-srcds-hl2mp.env
  test/update-hlds-cstrike.env
  test/update-srcds-hl2mp.env
Labels: area/ci, refactor, area/tests

#82 Fix (Dockerfile): Reduce condition to the value of `STEAM_LOGIN` for deciding between authenticated and anonymous logins
  build/Dockerfile
  update/Dockerfile
Labels: area/ci, refactor, fix

#83 Fix (ci): Fix processing of `STEAM_USERNAME` and `STEAM_PASSWORD` values
  build.sh
Labels: area/ci, fix

#84 Docs (ci): Update documentation on CI variables in `build.sh`
  build.sh
Labels: docs, area/ci

#85 Fix (ci): Fix extraction of `hlds-appmanifest` files in `build/Dockerfile`
  build/Dockerfile
Labels: area/ci, fix

#86 Feature (ci): Revise `FIX_APPMANIFEST` to independent from `INSTALL_COUNT` for improved control of application of `hlds` appmanifests
  build/Dockerfile
Labels: area/ci, feature

#87 Enhancement (ci): Improve clean-up in Dockerfiles
  build/Dockerfile
  update/Dockerfile
Labels: enhancement, area/ci

#88 Refactor (test): Use default `STEAM_LOGIN=` in `srcds` `.env` files
  test/build-srcds-hl2mp.env
  test/update-srcds-hl2mp.env
Labels: area/ci, area/tests

#89 Refactor (ci): Improve logic, debug output, and comments in Dockerfiles
  build/Dockerfile
  update/Dockerfile
Labels: area/ci, refactor

#90 Fix (ci): Fix shell dot source syntax
  .github/workflows/ci-master-pr.yml
Labels: area/ci, fix

#91 Docs (readme): Fix and update various sections
  README.md
Labels: docs, fix

#92 Style (Dockerfile): Tweak minor formatting inconsistency
  build/Dockerfile
  update/Dockerfile
Labels: style

#93 Refactor (ci): Rename docker build context variable
  build.sh
Labels: area/ci, refactor

#94 Refactor (ci): Improve sequence of default job variables to process
  build.sh
Labels: area/ci, refactor

#95 Refactor (ci): Use additional game image variables for improved abstraction and readibility
  build.sh
Labels: area/ci, refactor

#96 Refactor (test): Revise commands for getting the executing script's root directory for improved compatibility and portability
  test/test-game-image-game-version.sh
  test/test-game-image.sh
Labels: refactor, area/tests

#97 Refactor (Dockerfile): Add quotes for several variables
  build/Dockerfile
  update/Dockerfile
Labels: area/ci, refactor

#98 Refactor (Dockerfile): Single-quote hard-coded `tar` wildcard pattern
  build/Dockerfile
Labels: area/ci, refactor

#99 Fix (ci): Remove use of `docker build` `--cache-from` for clean images
  build.sh
Labels: fix

#100 Docs (readme): Tweak write-up on update duration
  README.md
Labels: docs, area/ci

#101 Docs (readme): Add links to main description
  README.md
Labels: docs
