Repository startersclan/docker-sourceservers, pull requests merged in 2023-11, with the labels that each got.

#154 Docs (examples): Fix command values in `docs/samples/docker-compose/docker-compose.binary.yml`
  docs/samples/docker-compose/docker-compose.binary.yml
Labels: docs

#153 Feature (ci): Add `srcds/cs2` support
  .generate/Generate-GameImageRepositoryReadme.ps1
  .github/workflows/ci-master-pr.yml
  README.md
  build.sh
  build/Dockerfile
  docs/image/readme/srcds-cs2.md
  docs/samples/docker-compose/docker-compose.bash-c.yml
  docs/samples/docker-compose/docker-compose.binary.yml
  test/srcds-cs2
  test/srcds-cs2-query
  test/test-game-image-game-version.sh
  test/test-game-image.sh
  update/Dockerfile
Labels: feature

#155 Fix: Fix test for `srcds/cs2` for CI environments
  build.sh
Labels: fix

#156 Docs (readme): Update docs on `ENTRYPOINT`, `CMD` and `WORKDIR`
  README.md
Labels: docs

#157 Refactor (ci): Remove unneeded `-i` for `srcds/cs2` test container
  build.sh
Labels: refactor

#158 Docs (examples): Simplify `entrypoint` syntax in `docs/samples/docker-compose/docker-compose.binary.yml`
  README.md
  docs/samples/docker-compose/docker-compose.binary.yml
Labels: docs

#159 Docs (examples): Use `exec` for game binary in `docs/samples/docker-compose/docker-compose.bash-c.yml`
  docs/samples/docker-compose/docker-compose.bash-c.yml
Labels: docs

#160 Docs (examples): Add additional examples to `docs/samples/docker-compose/docker-compose.bash-c.yml`
  docs/samples/docker-compose/docker-compose.bash-c.yml
Labels: docs

#161 Docs (examples): Standardize multi-line command values in `docs/samples/docker-compose/docker-compose.bash-c.yml`
  docs/samples/docker-compose/docker-compose.bash-c.yml
Labels: docs

#162 Docs (readme): Fix multi-line commands example reference
  README.md
Labels: docs

#163 Docs (examples): Use `/bin/bash` as entrypoint in `docs/samples/docker-compose/docker-compose.bash-c.yml`
  docs/samples/docker-compose/docker-compose.bash-c.yml
Labels: docs

#164 Docs (examples): Tweak multi-line commands example reference
  README.md
Labels: docs

#167 Enhancement (ci): Add support for `INSTALL_COUNT`
  build.sh
  test/build-hlds-cstrike.env
  test/build-srcds-hl2mp.env
  test/update-hlds-cstrike.env
  test/update-srcds-hl2mp.env
  update/Dockerfile
Labels: enhancement

#166 Fix (ci): Do not terminate prematurely without showing `GAME_IMAGE_VERSION_LINES` when verifying image fails
  build.sh
Labels: fix

#168 Fix (ci): Show error if `--env-file` does not exist
  build.sh
Labels: fix

#170 Enhancement (ci): Add date at start and end of script, and show dates in ISO format
  build.sh
Labels: enhancement

#172 Enhancement (ci): Add `NO_CACHE` env var
  build.sh
  test/build-hlds-cstrike.env
  test/build-srcds-hl2mp.env
  test/update-hlds-cstrike.env
  test/update-srcds-hl2mp.env
Labels: enhancement

#169 Fix: Hotfix 2023-11-23 hlds update
  .github/workflows/ci-master-pr.yml
  build/Dockerfile
  test/build-hlds-cstrike.env
  test/hlds-valve
  test/update-hlds-cstrike.env
  update/Dockerfile
Labels: fix
