Repository startersclan/docker-sourceservers, pull requests merged in 2023-12, with the labels that each got.

#173 Enhancement (ci): Add `<version>-layered-<date>` tag for layered image
  README.md
  build.sh
Labels: enhancement

#176 Refactor (ci): Rearrange and add missing variables in test `.env` files
  test/build-hlds-cstrike.env
  test/build-srcds-hl2mp.env
  test/update-hlds-cstrike.env
  test/update-srcds-hl2mp.env
Labels: refactor

#175 Enhancement (ci): Print tags at end of successful build
  build.sh
Labels: enhancement

#177 Docs: Deprecate need for `FIX_APPMANIFEST` for `hlds` in usage examples
  build.sh
Labels: docs

#152 Feature: Add `games.json` and script to create and update branches
  .generate/Generate-GameImageRepositoryReadme.ps1
  .github/workflows/ci-master-pr.yml
  .gitignore
  .gitlab-ci.yml
  Generate-GitBranches.Tests.ps1
  Generate-GitBranches.ps1
  README.md
  build.sh
  docs/image/readme/hlds-cstrike.md
  docs/image/readme/hlds-czero.md
  docs/image/readme/hlds-dmc.md
  docs/image/readme/hlds-dod.md
  docs/image/readme/hlds-gearbox.md
  docs/image/readme/hlds-ricochet.md
  docs/image/readme/hlds-tfc.md
  docs/image/readme/hlds-valve.md
  docs/image/readme/srcds-cs2.md
  docs/image/readme/srcds-csgo.md
  docs/image/readme/srcds-cstrike.md
  docs/image/readme/srcds-dod.md
  docs/image/readme/srcds-hl2mp.md
  docs/image/readme/srcds-left4dead.md
  docs/image/readme/srcds-left4dead2.md
  docs/image/readme/srcds-tf.md
  games.json
  notify.sh
Labels: feature

#178 Docs (ci): Fix build status badges
  .generate/Generate-GameImageRepositoryReadme.ps1
  README.md
  docs/image/readme/hlds-cstrike.md
  docs/image/readme/hlds-czero.md
  docs/image/readme/hlds-dmc.md
  docs/image/readme/hlds-dod.md
  docs/image/readme/hlds-gearbox.md
  docs/image/readme/hlds-ricochet.md
  docs/image/readme/hlds-tfc.md
  docs/image/readme/hlds-valve.md
  docs/image/readme/srcds-cs2.md
  docs/image/readme/srcds-csgo.md
  docs/image/readme/srcds-cstrike.md
  docs/image/readme/srcds-dod.md
  docs/image/readme/srcds-hl2mp.md
  docs/image/readme/srcds-left4dead.md
  docs/image/readme/srcds-left4dead2.md
  docs/image/readme/srcds-tf.md
Labels: docs

#179 Fix (ci): Comment out secret env vars in `.env` in generated branches
  Generate-GitBranches.ps1
Labels: fix

#180 Fix (ci): Run builds only on designated branches
  .gitlab-ci.yml
Labels: fix

#181 Fix (ci): Add job for the `.state` update commit to mirror latest build status
  .gitlab-ci.yml
  Generate-GitBranches.ps1
Labels: fix

#182 Docs (ci): Fix reference to game image build status badges
  README.md
Labels: docs

#184 Fix (ci): Add separate `BUILD_PAUSE` env var in `.state` to pause builds instead of using `BUILD_STATUS`
  Generate-GitBranches.ps1
Labels: fix

#183 Fix (ci): Run `state` job only on update `.state` commit
  .gitlab-ci.yml
Labels: fix

#185 Docs (readme): Fix documentation on `ENTRYPOINT`, `CMD`, and `WORKDIR`
  README.md
Labels: docs
