Repository startersclan/docker-sourceservers, pull requests merged in 2023-03, with the labels that each got.

#110 Fix (ci): Add label `game_version_base` to base images
  build.sh
Labels: area/ci, fix

#111 Enhancement (ci): Add `docker build` argument `CACHE_KEY`
  build.sh
  build/Dockerfile
  update/Dockerfile
Labels: enhancement, area/ci, fix

#112 Fix (ci): Ensure `test-build` jobs precede `test-update` jobs to correctly test incremental builds
  .github/workflows/ci-master-pr.yml
  build.sh
  test/update-hlds-cstrike.env
  test/update-srcds-hl2mp.env
Labels: area/ci, feature, fix

#113 Fix (ci): Retain `/root/Steam/appcache` for `hlds/*` games to not be re-downloaded entirely on `update`
  build/Dockerfile
  update/Dockerfile
Labels: area/ci, fix

#115 Fix (ci): Use `df -h || true` in `build.sh` for non-`sudo` environments
  build.sh
Labels: area/ci, fix

#116 Enhancement (ci): Add release drafter
  .github/release-drafter.yml
  .github/workflows/ci-master-pr.yml
Labels: enhancement, area/ci

#114 Enhancement (ci): Create artifact with base and layered size at end of `build.sh` and test `update` size
  build.sh
Labels: enhancement, area/ci

#118 Refactor (ci): Utilize `.build.state` artifact
  .circleci/config.yml
  .gitlab-ci.yml
  notify.sh
Labels: area/ci, refactor

#119 Enhancement (ci): Add `docker build --progress plain` to output full build log in terminal
  build.sh
Labels: enhancement

#120 Enhancement (ci): Add `commit_sha` label
  build.sh
Labels: enhancement, area/ci

#121 Fix (ci): Fix location of `NO_PULL` under CI variables in `build.sh`
  build.sh
Labels: area/ci, fix

#122 Fix (ci): Test game version only if necessary
  build.sh
Labels: fix

#124 Fix (ci): Add logging of `CLIENT_APPID` in `build` and fix logging tag in `update`
  build/Dockerfile
  update/Dockerfile
Labels: area/ci, fix

#125 Feature (ci): Add `./build.sh --env-file` param to build from an `.env` file
  .github/workflows/ci-master-pr.yml
  build.sh
Labels: area/ci, feature

#127 Fix (ci): Fix `REGISTRY_USER` and `REGISTRY_PASSWORD` to be optional when `NO_PUSH=true`
  build.sh
  test/build-hlds-cstrike.env
  test/build-srcds-hl2mp.env
Labels: area/ci, fix

#128 Enhancement (ci): Add `--help` to display usage
  build.sh
Labels: enhancement, area/ci

#129 Enhancement (ci): Use `set -u` in `build.sh`
  build.sh
Labels: enhancement, area/ci

#130 Enhancement (test): Use a temp directory for test
  build.sh
Labels: enhancement, area/tests

#132 Enhancement (ci): Add validation for `PIPELINE`
  build.sh
Labels: enhancement, area/ci

#131 Enhancement (ci): Use `docker build` secrets within context of `docker build`
  build.sh
Labels: enhancement, area/ci

#134 Refactor (ci): Improve tagging of images on `update`
  build.sh
Labels: area/ci, refactor

#137 Enhancement (ci): Add `DOCKER_REPOSITORY` env var and deprecate `REGISTRY_GOLDSOURCE` and `REGISTRY_SOURCE` env vars
  build.sh
  test/build-hlds-cstrike.env
  test/build-srcds-hl2mp.env
  test/update-hlds-cstrike.env
  test/update-srcds-hl2mp.env
Labels: enhancement, area/ci

#136 Enhancement (ci): Add more usage in `build.sh`
  build.sh
Labels: enhancement, area/ci

#138 Fix (ci): Fix types in `build.sh` usage
  build.sh
Labels: fix

#140 Enhancement (ci): Improve readability of tagging for `PIPELINE=update`
  build.sh
Labels: enhancement

#141 Enhancement (ci): Tweak validation for variable `PIPELINE`
  build.sh
Labels: enhancement
